# Generated by Django 5.2.9 on 2025-12-03 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(max_length=600)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='copyrights.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Registo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registo', models.CharField(max_length=10, null=True, unique=True)),
                ('estado', models.CharField(choices=[('REJEITADO', 'Rejeitado'), ('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado')], default='PENDENTE', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(max_length=600)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agente_registrador', to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registos', to='copyrights.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='arquivo')),
                ('actualizado_em', models.DateTimeField(auto_now_add=True)),
                ('registo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='copyrights.registo')),
            ],
        ),
    ]
