# Generated by Django 5.2.9 on 2025-12-03 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyrights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='titulo',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='registo',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agente_registrador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registo',
            name='estado',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('REJEITADO', 'Rejeitado'), ('APROVADO', 'Aprovado')], default='PENDENTE', max_length=10),
        ),
    ]
