# Generated by Django 5.2.9 on 2025-12-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyrights', '0002_alter_obra_titulo_alter_registo_agente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registo',
            name='estado',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10),
        ),
    ]
