# Generated by Django 5.2.9 on 2025-12-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyrights', '0003_alter_registo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registo',
            name='estado',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('PENDENTE', 'Pendente'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10),
        ),
    ]
